### ISSUE TITLE
ValueError: unsupported pickle protocol: 5

### ISSUE THREAD

**Issue by vamWu** [caiyuanhao1998/X-Gaussian#5]
Thank you for your outstanding work.
I found this error " ValueError: unsupported pickle protocol: 5" while running my training.
As far as I know, Python 3.7.13 version is not supporting pickle protocol 5. I was able to fix it by simply upgrading python version greater than 3.8. But the environment.yaml requires for 3.7.13.

**Comment by caiyuanhao1998** [comment]
Hi, did you install the environment as described in the `README.md` file? Because I did not encounter this issue.

**Comment by vamWu** [comment]
Yes, I created the environment using conda env create --file environment.yml, so it should match README.md.
I've currently resolved this error by upgrading python with dependencies to python 3.8, so I apologise for not being able to output the original detailed environment information. My full output at that time was as follows, just for reference.
``` bash
python --version

Python 3.7.13

python train.py --config config/foot.yaml --eval 

Optimizing 
Output folder: ./output/foot/2024_09_03_19_00_48 [03/09 19:00:48]
2024-09-03 19:00:48,659 - INFO: Training parameters: {'iterations': 20000, 'position_lr_init': 0.000179, 'position_lr_final': 1.79e-06, 'position_lr_delay_mult': 0.01, 'position_lr_max_steps': 20000, 'feature_lr': 0.002, 'opacity_lr': 0.006, 'radiodensity_lr': 0.05, 'scaling_lr': 0.005, 'rotation_lr': 0.001, 'percent_dense': 0.008, 'lambda_dssim': 0.2, 'densification_interval': 800, 'opacity_reset_interval': 1200, 'radiodensity_reset_interval': 3000, 'densify_from_iter': 500, 'densify_until_iter': 8000, 'densify_grad_threshold': 2.7e-05, 'random_background': False}
/media/newLinDisk/Reproduce/X-Gaussian/data/foot_50.pickle [03/09 19:00:48]
Loading pickle file for X-ray rendering [03/09 19:00:48]
Reading Training Transforms [03/09 19:00:48]
Traceback (most recent call last):
  File "train.py", line 206, in <module>
    training(lp.extract(args), op.extract(args), pp.extract(args), args.test_iterations, args.save_iterations, args.checkpoint_iterations, args.start_checkpoint, args.debug_from)
  File "train.py", line 27, in training
    scene = Scene(dataset, gaussians)
  File "/media/newLinDisk/Reproduce/X-Gaussian/scene/__init__.py", line 42, in __init__
    scene_info, self.volume_positions, self.image_3d = sceneLoadTypeCallbacks["Xray"](path = args.source_path, eval = args.eval, interval = args.interval, add_num = args.add_num, train_num = args.train_num)
  File "/media/newLinDisk/Reproduce/X-Gaussian/scene/dataset_readers.py", line 414, in Xray_readNerfSyntheticInfo
    train_cam_infos = Xray_readCamerasFromTransforms(path, type = "train")
  File "/media/newLinDisk/Reproduce/X-Gaussian/scene/dataset_readers.py", line 346, in Xray_readCamerasFromTransforms
    data = pickle.load(handle)
ValueError: unsupported pickle protocol: 5

```

**Comment by zyuxiang0822** [comment]
Thank you for your outstanding work. I meet the same issue.
3.7.13 (default, Oct 18 2022, 18:57:03) 
[GCC 11.2.0]
Optimizing 
Output folder: ./output/chest/2024_09_03_15_14_26 [03/09 15:14:26]
2024-09-03 15:14:26,842 - INFO: Training parameters: {'iterations': 20000, 'position_lr_init': 0.00019, 'position_lr_final': 1.9e-06, 'position_lr_delay_mult': 0.01, 'position_lr_max_steps': 20000, 'feature_lr': 0.002, 'opacity_lr': 0.008, 'radiodensity_lr': 0.05, 'scaling_lr': 0.005, 'rotation_lr': 0.001, 'percent_dense': 0.01, 'lambda_dssim': 0.2, 'densification_interval': 200, 'opacity_reset_interval': 4000, 'radiodensity_reset_interval': 2000, 'densify_from_iter': 500, 'densify_until_iter': 8000, 'densify_grad_threshold': 2.6e-05, 'random_background': False}
/home/ubuntu/X-Gaussian/data/chest_50.pickle [03/09 15:14:26]
Loading pickle file for X-ray rendering [03/09 15:14:26]
Reading Training Transforms [03/09 15:14:26]
Traceback (most recent call last):
  File "train.py", line 206, in <module>
    training(lp.extract(args), op.extract(args), pp.extract(args), args.test_iterations, args.save_iterations, args.checkpoint_iterations, args.start_checkpoint, args.debug_from)
  File "train.py", line 27, in training
    scene = Scene(dataset, gaussians)
  File "/home/ubuntu/X-Gaussian/scene/__init__.py", line 42, in __init__
    scene_info, self.volume_positions, self.image_3d = sceneLoadTypeCallbacks["Xray"](path = args.source_path, eval = args.eval, interval = args.interval, add_num = args.add_num, train_num = args.train_num)
  File "/home/ubuntu/X-Gaussian/scene/dataset_readers.py", line 414, in Xray_readNerfSyntheticInfo
    train_cam_infos = Xray_readCamerasFromTransforms(path, type = "train")
  File "/home/ubuntu/X-Gaussian/scene/dataset_readers.py", line 346, in Xray_readCamerasFromTransforms
    data = pickle.load(handle)
ValueError: unsupported pickle protocol: 5

**Comment by caiyuanhao1998** [comment]
Hi! I have re-dumped the pickle data according to protocol 4 for your convinience. I have updated the link of the data and provided the code for pickle re-dumping. Free free to check.

If you find our repo useful, please help us star it. Thanks :)

**Comment by byungjur96** [comment]
I've suffered same problem, and I found it that in python 3.7, I needed to use `pickle5` rather than `pickle`.
So I've installed `pickle5` with `conda install pickle5` and replace `import pickle` line in `dataset_readers.py` as `import pickle5 as pickle`
this could also be a quick solution

**Comment by caiyuanhao1998** [comment]
Thanks for this information. I have re-dumped the pickle data and now it can run smoothly

**Comment by vamWu** [comment]
> <img alt="截屏2024-09-03 上午10 00 29" width="1050" src="https://private-user-images.githubusercontent.com/48472661/364013415-82c53544-ff00-4f1d-b59a-6219c6bd4ec7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU0MzEyNTEsIm5iZiI6MTcyNTQzMDk1MSwicGF0aCI6Ii80ODQ3MjY2MS8zNjQwMTM0MTUtODJjNTM1NDQtZmYwMC00ZjFkLWI1OWEtNjIxOWM2YmQ0ZWM3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA0VDA2MjIzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTljNzJiODRhMTljNzkwZWQ1YjcwZTUxYjI4MzliYzhiOTBkMWU2NTJmOTE4Nzk0OTFlNjg4YjdiNTA1MTY5NzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Kf4Sp7PjJUeGP8aohpmUiUauNCV3eQCqU2vDgvFgT6s">
> I set a breakpoint at line 346 of `dataset_readers.py` to test the pickle package. My python is 3.7.13 and it can load the pickle data with its inherent pickle package. It is wierd.
> 
> If you use python 3.8. Can you train the model normally? To match our training log?

Thank you for your reply and help, I was able to complete the subsequent training using python 3.8 (cuda 11.6) and the results of the evaluations have changed slightly compared to your logs. For chest it is as follows
```
2024-09-03 21:50:57,070 - INFO: Testing Speed: 236.44747909107923 fps
2024-09-03 21:50:57,070 - INFO: Testing Time: 0.21146345138549805 s
2024-09-03 21:50:57,070 - INFO: 
[ITER 20000] Evaluating test: SSIM = 0.9998459649085999, PSNR = 43.79974006652832
2024-09-03 21:50:57,070 - INFO: Iter:20000, total_points:322148
2024-09-03 21:50:57,072 - INFO: 
[ITER 20000] Saving Gaussians


```
